eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
ra: hehe
    
spring.datasource.url=jdbc:mysql://localhost:3306/uber1
spring.datasource.username=root
spring.datasource.password=ez60
spring.jpa.show-sql=true
  
